spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/springpractice #띄어쓰기 4칸 #;MVCC=TRUE옵션을 넣어주면 여러개가 한번에 접근했을 때 좀 더 빨리 처리됨
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
#  org.hibernate.type: trace #스프링 부트 2.x, hibernate5 #띄어쓰기 2칸
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6 #띄어쓰기 2칸